<?php

// Composer: "fzaninotto/faker": "v1.3.0"
use Faker\Factory as Faker;

class IncomeSummaryTableSeeder extends Seeder {

	public function run()
	{
		DB::table('repincomefromcontracts')->truncate();

		DB::table('repincomefromcontracts')->insert(
                        array(
                                array('contractTitle' => 'Delfin Hermanos Inc.',
                                	'incomeJanuary' => '350000',
                                	'incomeFebruary' => '1200000',
                                	'incomeMarch' => '3756437.50',
                                	'incomeApril' => '1100000',
                                	'incomeMay' => '3200000',
                                	'incomeJune' => '2100000',
                                	'incomeJuly' => '6500000',
                                	'incomeAugust' => '2500000',
                                	'incomeSeptember' => '100000',
                                	'incomeOctober' => '2274200',
                                	'incomeNovember' => '140000',
                                	'incomeDecember' => '3108200',
                                	'incomeTotal' => '0',
                                	'created_at' => date('Y-m-d H:i:s'),
                                	'updated_at' => date('Y-m-d H:i:s')),

                            	array('contractTitle' => 'Dolmar Property Ventures',
                                	'incomeJanuary' => '751256.15',
                                	'incomeFebruary' => '0',
                                	'incomeMarch' => '2837105.60',
                                	'incomeApril' => '2267342.88',
                                	'incomeMay' => '889892.66',
                                	'incomeJune' => '492814',
                                	'incomeJuly' => '989533.19',
                                	'incomeAugust' => '984417.17',
                                	'incomeSeptember' => '1893077.33',
                                	'incomeOctober' => '2187403.70',
                                	'incomeNovember' => '944219.05',
                                	'incomeDecember' => '1097235.81',
                                	'incomeTotal' => '15304297.54',
                                	'created_at' => date('Y-m-d H:i:s'),
                                	'updated_at' => date('Y-m-d H:i:s')), 

                            	array('contractTitle' => 'Pallas Homes Inc.',
                                	'incomeJanuary' => '85000',
                                	'incomeFebruary' => '92768.04',
                                	'incomeMarch' => '383738.93',
                                	'incomeApril' => '0',
                                	'incomeMay' => '0',
                                	'incomeJune' => '0',
                                	'incomeJuly' => '0',
                                	'incomeAugust' => '0',
                                	'incomeSeptember' => '0',
                                	'incomeOctober' => '0',
                                	'incomeNovember' => '0',
                                	'incomeDecember' => '26352.98',
                                	'incomeTotal' => '587859.95',
                                	'created_at' => date('Y-m-d H:i:s'),
                                	'updated_at' => date('Y-m-d H:i:s')), 

                            	array('contractTitle' => 'D.L. Lazaro, Inc.',
                                	'incomeJanuary' => '0',
                                	'incomeFebruary' => '0',
                                	'incomeMarch' => '0',
                                	'incomeApril' => '0',
                                	'incomeMay' => '0',
                                	'incomeJune' => '0',
                                	'incomeJuly' => '0',
                                	'incomeAugust' => '0',
                                	'incomeSeptember' => '0',
                                	'incomeOctober' => '0',
                                	'incomeNovember' => '499699.01',
                                	'incomeDecember' => '539600.52',
                                	'incomeTotal' => '1039233.53',
                                	'created_at' => date('Y-m-d H:i:s'),
                                	'updated_at' => date('Y-m-d H:i:s')),                                        
                        ));

		DB::table('repcostpurchase')->truncate();

		DB::table('repcostpurchase')->insert(
                        array(
                                array('purchaseJanuary' => '248037.26',
                                	'purchaseFebruary' => '883334.84',
                                	'purchaseMarch' => '1915851.17',
                                	'purchaseApril' => '1504815.48',
                                	'purchaseMay' => '1637298.71',
                                	'purchaseJune' => '1460411.03',
                                	'purchaseJuly' => '3129800.68',
                                	'purchaseAugust' => '1909848.06',
                                	'purchaseSeptember' => '1589174.73',
                                	'purchaseOctober' => '1764281.95',
                                	'purchaseNovember' => '1451534.46',
                                	'purchaseDecember' => '663099.18',
                                	'purchaseTotal' => '18157487.55',
                                	'created_at' => date('Y-m-d H:i:s'),
                                	'updated_at' => date('Y-m-d H:i:s')),                                  
                        ));

		DB::table('repcostsubcon')->truncate();

		DB::table('repcostsubcon')->insert(
                        array(
                                array('subconJanuary' => '766567.41',
                                	'subconFebruary' => '748329.05',
                                	'subconMarch' => '863641.10',
                                	'subconApril' => '557910.00',
                                	'subconMay' => '594993.15',
                                	'subconJune' => '828329.22',
                                	'subconJuly' => '842888.36',
                                	'subconAugust' => '764109.90',
                                	'subconSeptember' => '1000269.38',
                                	'subconOctober' => '615614.01',
                                	'subconNovember' => '573937.88',
                                	'subconDecember' => '561732.12',
                                	'subconTotal' => '8718294.58',
                                	'created_at' => date('Y-m-d H:i:s'),
                                	'updated_at' => date('Y-m-d H:i:s')),                                  
                        ));

		DB::table('repcostinhouse')->truncate();

		DB::table('repcostinhouse')->insert(
                        array(
                                array('inhouseJanuary' => '0',
                                	'inhouseFebruary' => '0',
                                	'inhouseMarch' => '0',
                                	'inhouseApril' => '0',
                                	'inhouseMay' => '0',
                                	'inhouseJune' => '0',
                                	'inhouseJuly' => '0',
                                	'inhouseAugust' => '21725',
                                	'inhouseSeptember' => '35332.50',
                                	'inhouseOctober' => '36832.5',
                                	'inhouseNovember' => '26684.69',
                                	'inhouseDecember' => '52931.88',
                                	'inhouseTotal' => '173506.57',
                                	'created_at' => date('Y-m-d H:i:s'),
                                	'updated_at' => date('Y-m-d H:i:s')),                                  
                        ));

		DB::table('repcosttrucking')->truncate();

		DB::table('repcosttrucking')->insert(
                        array(
                                array('truckingJanuary' => '14000',
                                	'truckingFebruary' => '25900',
                                	'truckingMarch' => '5390',
                                	'truckingApril' => '250',
                                	'truckingMay' => '0',
                                	'truckingJune' => '0',
                                	'truckingJuly' => '4700',
                                	'truckingAugust' => '300',
                                	'truckingSeptember' => '1100',
                                	'truckingOctober' => '0',
                                	'truckingNovember' => '55053.55',
                                	'truckingDecember' => '8848.5',
                                	'truckingTotal' => '115542.05',
                                	'created_at' => date('Y-m-d H:i:s'),
                                	'updated_at' => date('Y-m-d H:i:s')),                                  
                        ));

		DB::table('repcostformworks')->truncate();

		DB::table('repcostformworks')->insert(
                        array(
                                array('formworksJanuary' => '16500.01',
                                	'formworksFebruary' => '7333.33',
                                	'formworksMarch' => '12833.33',
                                	'formworksApril' => '7166.67',
                                	'formworksMay' => '15400.38',
                                	'formworksJune' => '29166.67',
                                	'formworksJuly' => '19001.01',
                                	'formworksAugust' => '0',
                                	'formworksSeptember' => '5500.00',
                                	'formworksOctober' => '0',
                                	'formworksNovember' => '0',
                                	'formworksDecember' => '0',
                                	'formworksTotal' => '112901.40',
                                	'created_at' => date('Y-m-d H:i:s'),
                                	'updated_at' => date('Y-m-d H:i:s')),                                  
                        ));

		DB::table('repsalarymonthly')->truncate();

		DB::table('repsalarymonthly')->insert(
                        array(
                                array('monthlyJanuary' => '98511.91',
                                	'monthlyFebruary' => '118478.47',
                                	'monthlyMarch' => '167324.45',
                                	'monthlyApril' => '58098.72',
                                	'monthlyMay' => '136102.71',
                                	'monthlyJune' => '138283.92',
                                	'monthlyJuly' => '117311.71',
                                	'monthlyAugust' => '138614.33',
                                	'monthlySeptember' => '164458.95',
                                	'monthlyOctober' => '148187.78',
                                	'monthlyNovember' => '73783.08',
                                	'monthlyDecember' => '154851.08',
                                	'monthlyTotal' => '1514007.11',
                                	'created_at' => date('Y-m-d H:i:s'),
                                	'updated_at' => date('Y-m-d H:i:s')),                                  
                        ));

		DB::table('repsalaryweekly')->truncate();

		DB::table('repsalaryweekly')->insert(
                        array(
                                array('weeklyJanuary' => '22897.50',
                                	'weeklyFebruary' => '23645',
                                	'weeklyMarch' => '22490',
                                	'weeklyApril' => '18405',
                                	'weeklyMay' => '22290',
                                	'weeklyJune' => '17220',
                                	'weeklyJuly' => '20080',
                                	'weeklyAugust' => '17528',
                                	'weeklySeptember' => '22955',
                                	'weeklyOctober' => '19512',
                                	'weeklyNovember' => '19139',
                                	'weeklyDecember' => '17634',
                                	'weeklyTotal' => '243765.5',
                                	'created_at' => date('Y-m-d H:i:s'),
                                	'updated_at' => date('Y-m-d H:i:s')),                                  
                        ));

		DB::table('repotherexps')->truncate();

		DB::table('repotherexps')->insert(
                        array(
                                array('otherexpsTitle' => 'Bae Proj.',
                                	'otherexpsJanuary' => '0',
                                	'otherexpsFebruary' => '0',
                                	'otherexpsMarch' => '0',
                                	'otherexpsApril' => '0',
                                	'otherexpsMay' => '0',
                                	'otherexpsJune' => '0',
                                	'otherexpsJuly' => '0',
                                	'otherexpsAugust' => '0',
                                	'otherexpsSeptember' => '0',
                                	'otherexpsOctober' => '41368.81',
                                	'otherexpsNovember' => '181362.32',
                                	'otherexpsDecember' => '300823.54',
                                	'otherexpsTotal' => '523548.67',
                                	'created_at' => date('Y-m-d H:i:s'),
                                	'updated_at' => date('Y-m-d H:i:s')),

                            	array('otherexpsTitle' => 'Pallas Blk 14 Lot 1',
                                	'otherexpsJanuary' => '183517.50',
                                	'otherexpsFebruary' => '372804.24',
                                	'otherexpsMarch' => '188742.68',
                                	'otherexpsApril' => '134234.25',
                                	'otherexpsMay' => '9040',
                                	'otherexpsJune' => '208273.6',
                                	'otherexpsJuly' => '211928.17',
                                	'otherexpsAugust' => '448460.96',
                                	'otherexpsSeptember' => '433580.83',
                                	'otherexpsOctober' => '310753.15',
                                	'otherexpsNovember' => '18898.75',
                                	'otherexpsDecember' => '1774.25',
                                	'otherexpsTotal' => '3122008.38',
                                	'created_at' => date('Y-m-d H:i:s'),
                                	'updated_at' => date('Y-m-d H:i:s')), 

                            	array('otherexpsTitle' => 'Pallas Blk 9 Lot 22',
                                	'otherexpsJanuary' => '0',
                                	'otherexpsFebruary' => '0',
                                	'otherexpsMarch' => '0',
                                	'otherexpsApril' => '11510',
                                	'otherexpsMay' => '231208.12',
                                	'otherexpsJune' => '37271',
                                	'otherexpsJuly' => '13000',
                                	'otherexpsAugust' => '0',
                                	'otherexpsSeptember' => '34414',
                                	'otherexpsOctober' => '2000',
                                	'otherexpsNovember' => '3570',
                                	'otherexpsDecember' => '165',
                                	'otherexpsTotal' => '333138.12',
                                	'created_at' => date('Y-m-d H:i:s'),
                                	'updated_at' => date('Y-m-d H:i:s')),   

                            	array('otherexpsTitle' => 'Pallas Blk 9 Lot 20',
                                	'otherexpsJanuary' => '0',
                                	'otherexpsFebruary' => '0',
                                	'otherexpsMarch' => '0',
                                	'otherexpsApril' => '0',
                                	'otherexpsMay' => '0',
                                	'otherexpsJune' => '0',
                                	'otherexpsJuly' => '0',
                                	'otherexpsAugust' => '0',
                                	'otherexpsSeptember' => '5095',
                                	'otherexpsOctober' => '63941.5',
                                	'otherexpsNovember' => '33897.25',
                                	'otherexpsDecember' => '1800',
                                	'otherexpsTotal' => '104733.75',
                                	'created_at' => date('Y-m-d H:i:s'),
                                	'updated_at' => date('Y-m-d H:i:s')),    

                            	array('otherexpsTitle' => 'Pallas-Makati',
                                	'otherexpsJanuary' => '0',
                                	'otherexpsFebruary' => '11910',
                                	'otherexpsMarch' => '1325',
                                	'otherexpsApril' => '0',
                                	'otherexpsMay' => '0',
                                	'otherexpsJune' => '0',
                                	'otherexpsJuly' => '0',
                                	'otherexpsAugust' => '0',
                                	'otherexpsSeptember' => '0',
                                	'otherexpsOctober' => '0',
                                	'otherexpsNovember' => '0',
                                	'otherexpsDecember' => '0',
                                	'otherexpsTotal' => '13262',
                                	'created_at' => date('Y-m-d H:i:s'),
                                	'updated_at' => date('Y-m-d H:i:s')),   

                            	array('otherexpsTitle' => 'United',
                                	'otherexpsJanuary' => '20257',
                                	'otherexpsFebruary' => '0',
                                	'otherexpsMarch' => '0',
                                	'otherexpsApril' => '755',
                                	'otherexpsMay' => '0',
                                	'otherexpsJune' => '0',
                                	'otherexpsJuly' => '0',
                                	'otherexpsAugust' => '0',
                                	'otherexpsSeptember' => '0',
                                	'otherexpsOctober' => '0',
                                	'otherexpsNovember' => '0',
                                	'otherexpsDecember' => '0',
                                	'otherexpsTotal' => '21012',
                                	'created_at' => date('Y-m-d H:i:s'),
                                	'updated_at' => date('Y-m-d H:i:s')),  

                            	array('otherexpsTitle' => 'Condo',
                                	'otherexpsJanuary' => '0',
                                	'otherexpsFebruary' => '0',
                                	'otherexpsMarch' => '39065.62',
                                	'otherexpsApril' => '31139',
                                	'otherexpsMay' => '0',
                                	'otherexpsJune' => '12590',
                                	'otherexpsJuly' => '0',
                                	'otherexpsAugust' => '0',
                                	'otherexpsSeptember' => '0',
                                	'otherexpsOctober' => '0',
                                	'otherexpsNovember' => '0',
                                	'otherexpsDecember' => '0',
                                	'otherexpsTotal' => '82794.62',
                                	'created_at' => date('Y-m-d H:i:s'),
                                	'updated_at' => date('Y-m-d H:i:s')),   

                            	array('otherexpsTitle' => 'Garden Villas',
                                	'otherexpsJanuary' => '0',
                                	'otherexpsFebruary' => '0',
                                	'otherexpsMarch' => '23057',
                                	'otherexpsApril' => '490',
                                	'otherexpsMay' => '0',
                                	'otherexpsJune' => '0',
                                	'otherexpsJuly' => '0',
                                	'otherexpsAugust' => '0',
                                	'otherexpsSeptember' => '0',
                                	'otherexpsOctober' => '0',
                                	'otherexpsNovember' => '0',
                                	'otherexpsDecember' => '0',
                                	'otherexpsTotal' => '23547',
                                	'created_at' => date('Y-m-d H:i:s'),
                                	'updated_at' => date('Y-m-d H:i:s')),   

                            	array('otherexpsTitle' => 'Novaliches',
                                	'otherexpsJanuary' => '20660.8',
                                	'otherexpsFebruary' => '0',
                                	'otherexpsMarch' => '7770',
                                	'otherexpsApril' => '8000',
                                	'otherexpsMay' => '0',
                                	'otherexpsJune' => '0',
                                	'otherexpsJuly' => '0',
                                	'otherexpsAugust' => '0',
                                	'otherexpsSeptember' => '0',
                                	'otherexpsOctober' => '0',
                                	'otherexpsNovember' => '0',
                                	'otherexpsDecember' => '0',
                                	'otherexpsTotal' => '36430',
                                	'created_at' => date('Y-m-d H:i:s'),
                                	'updated_at' => date('Y-m-d H:i:s')),   

                            	array('otherexpsTitle' => 'Evergreen-Jubilation',
                                	'otherexpsJanuary' => '0',
                                	'otherexpsFebruary' => '0',
                                	'otherexpsMarch' => '0',
                                	'otherexpsApril' => '0',
                                	'otherexpsMay' => '5075.5',
                                	'otherexpsJune' => '5764',
                                	'otherexpsJuly' => '0',
                                	'otherexpsAugust' => '0',
                                	'otherexpsSeptember' => '0',
                                	'otherexpsOctober' => '0',
                                	'otherexpsNovember' => '0',
                                	'otherexpsDecember' => '0',
                                	'otherexpsTotal' => '10839.5',
                                	'created_at' => date('Y-m-d H:i:s'),
                                	'updated_at' => date('Y-m-d H:i:s')),  

                            	array('otherexpsTitle' => 'House',
                                	'otherexpsJanuary' => '0',
                                	'otherexpsFebruary' => '0',
                                	'otherexpsMarch' => '0',
                                	'otherexpsApril' => '0',
                                	'otherexpsMay' => '0',
                                	'otherexpsJune' => '0',
                                	'otherexpsJuly' => '19400',
                                	'otherexpsAugust' => '0',
                                	'otherexpsSeptember' => '0',
                                	'otherexpsOctober' => '0',
                                	'otherexpsNovember' => '0',
                                	'otherexpsDecember' => '0',
                                	'otherexpsTotal' => '19400',
                                	'created_at' => date('Y-m-d H:i:s'),
                                	'updated_at' => date('Y-m-d H:i:s')),  

                            	array('otherexpsTitle' => 'Club Ultima',
                                	'otherexpsJanuary' => '5834',
                                	'otherexpsFebruary' => '5834',
                                	'otherexpsMarch' => '5834',
                                	'otherexpsApril' => '5834',
                                	'otherexpsMay' => '19274',
                                	'otherexpsJune' => '5834',
                                	'otherexpsJuly' => '5834',
                                	'otherexpsAugust' => '5834',
                                	'otherexpsSeptember' => '5834',
                                	'otherexpsOctober' => '5834',
                                	'otherexpsNovember' => '5834',
                                	'otherexpsDecember' => '5834',
                                	'otherexpsTotal' => '96168',
                                	'created_at' => date('Y-m-d H:i:s'),
                                	'updated_at' => date('Y-m-d H:i:s')),   

                            	array('otherexpsTitle' => 'Starex',
                                	'otherexpsJanuary' => '36169',
                                	'otherexpsFebruary' => '36169',
                                	'otherexpsMarch' => '36169',
                                	'otherexpsApril' => '36169',
                                	'otherexpsMay' => '36169',
                                	'otherexpsJune' => '36169',
                                	'otherexpsJuly' => '0',
                                	'otherexpsAugust' => '0',
                                	'otherexpsSeptember' => '0',
                                	'otherexpsOctober' => '0',
                                	'otherexpsNovember' => '0',
                                	'otherexpsDecember' => '0',
                                	'otherexpsTotal' => '217014',
                                	'created_at' => date('Y-m-d H:i:s'),
                                	'updated_at' => date('Y-m-d H:i:s')), 

                            	array('otherexpsTitle' => 'Bulusan Travel & Tours',
                                	'otherexpsJanuary' => '0',
                                	'otherexpsFebruary' => '0',
                                	'otherexpsMarch' => '0',
                                	'otherexpsApril' => '134398',
                                	'otherexpsMay' => '0',
                                	'otherexpsJune' => '0',
                                	'otherexpsJuly' => '0',
                                	'otherexpsAugust' => '0',
                                	'otherexpsSeptember' => '0',
                                	'otherexpsOctober' => '0',
                                	'otherexpsNovember' => '0',
                                	'otherexpsDecember' => '0',
                                	'otherexpsTotal' => '134398',
                                	'created_at' => date('Y-m-d H:i:s'),
                                	'updated_at' => date('Y-m-d H:i:s')),     

                            	array('otherexpsTitle' => 'Verdana',
                                	'otherexpsJanuary' => '37000',
                                	'otherexpsFebruary' => '37000',
                                	'otherexpsMarch' => '37000',
                                	'otherexpsApril' => '37000',
                                	'otherexpsMay' => '37000',
                                	'otherexpsJune' => '37000',
                                	'otherexpsJuly' => '37000',
                                	'otherexpsAugust' => '37000',
                                	'otherexpsSeptember' => '37000',
                                	'otherexpsOctober' => '37000',
                                	'otherexpsNovember' => '37000',
                                	'otherexpsDecember' => '37000',
                                	'otherexpsTotal' => '444000',
                                	'created_at' => date('Y-m-d H:i:s'),
                                	'updated_at' => date('Y-m-d H:i:s')),                      
                        ));

// DB::table('repcostsubcon')->truncate();

		// DB::table('repcostsubcon')->insert(
  //                       array(
  //                               array('subconJanuary' => '',
  //                               	'subconFebruary' => '',
  //                               	'subconMarch' => '',
  //                               	'subconApril' => '',
  //                               	'subconMay' => '',
  //                               	'subconJune' => '',
  //                               	'subconJuly' => '',
  //                               	'subconAugust' => '',
  //                               	'subconSeptember' => '',
  //                               	'subconOctober' => '',
  //                               	'subconNovember' => '',
  //                               	'subconDecember' => '',
  //                               	'subconTotal' => '',
  //                               	'created_at' => date('Y-m-d H:i:s'),
  //                               	'updated_at' => date('Y-m-d H:i:s')),                                  
  //                       ));

	}

}